---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: .
  project:
    - ./tsconfig.json

ignorePatterns:
  - app/
  - dist/

plugins:
  - '@typescript-eslint'
  - prettier

env:
  es6: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
