name: Check Colab Notebook
on:
  schedule:
    - cron: '* * 1 * *'
  pull_request:
    # Check all PR

jobs:
  pull-notebook:
    runs-on: ubuntu-latest
    steps:
      # Pulls the Notebook from the Google Collab URL
      - name: wget-notebook
        uses: wei/wget@v1
        with:
          args: -O downloaded_file.ipynb 'https://docs.google.com/uc?export=download&id='1NU0gjtaHcB5Oc3NbFZiQYtctY2190hDu
      # Pulls an example dataset from rascaline's repository
      - name: wget-dataset
        uses: wei/wget@v1
        with:
          args: -O frames.xyz 'https://raw.githubusercontent.com/Luthaf/rascaline/a7af348694d5268b05a89c4773b3f51211e3b344/docs/static/dataset.xyz'
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          pip install wheel numpy tqdm jupyter nbconvert
          pip install ase chemiscope sklearn skcosmo
          pip install git+https://github.com/lab-cosmo/librascal
      # Checks that the notebook can run without errors
      - name: run notebook
        run: |
          jupyter nbconvert --to notebook --execute downloaded_file.ipynb
