name: Build Python wheel

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    # Check all PR

jobs:
  build-wheels:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: install dependencies
        run: python -m pip install build

      - name: build wheel
        run: python -m build .

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: |
            dist/*.tar.gz
            dist/*.whl

      - name: upload wheel & sdist to GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
